const jwt = require('jsonwebtoken');

// Admin routes: require Authorization: Bearer <ADMIN_API_KEY>
function requireAdmin(req, res, next) {
  const header = req.headers['authorization'] || '';
  const token = header.startsWith('Bearer ') ? header.slice(7) : null;

  if (!token || token !== process.env.ADMIN_API_KEY) {
    return res.status(401).json({ error: 'Unauthorized' });
  }
  next();
}

// Clinic dashboard routes: require a valid clinic session JWT
// (generated by POST /api/clinic/auth/token for email/password, or embedded in email links)
function requireClinicAccess(req, res, next) {
  const header = req.headers['authorization'] || '';
  const token = header.startsWith('Bearer ') ? header.slice(7) : null;

  if (!token) {
    return res.status(401).json({ error: 'Unauthorized' });
  }

  try {
    const payload = jwt.verify(token, process.env.JWT_SECRET);
    if (payload.type !== 'clinic_session') {
      return res.status(401).json({ error: 'Unauthorized' });
    }
    // Verify the token is scoped to the requested clinic
    if (payload.clinic_id !== req.params.clinic_id) {
      return res.status(403).json({ error: 'Forbidden' });
    }
    req.clinicId = payload.clinic_id;
    next();
  } catch {
    return res.status(401).json({ error: 'Session expired' });
  }
}

module.exports = { requireAdmin, requireClinicAccess };
